export const EVENT = {
  UPDATE_STATE_FROM_SERVER: 'UPDATE_STATE_FROM_SERVER',
  UPDATE_STATE_FROM_CLIENT: 'UPDATE_STATE_FROM_CLIENT',
  TIME_SYNC_BACKWARD: 'TIME_SYNC_BACKWARD',
  TIME_SYNC_FORWARD: 'TIME_SYNC_FORWARD',
  READY: 'READY',
  NOT_READY: 'NOT_READY'
}
